project:
  type: website
  output-dir: docs
  
website:
  title: "T.J Prescod-Heath"
  search: false
  navbar:
    background: light
    collapse: false
    right:
      - href: education/index_edu.qmd
        text: EDUCATION
      - href: internship/internship.qmd
        text: INTERNSHIP
      - href: test-blog/index.qmd
        text: BLOG
      - href: projects/project.qmd
        text: PROJECTS
      - href: courses/index_course.qmd
        text: COURSES
        
        
  page-footer:
    border: true
    right: "© 2023, T.J Prescod-Heath"
    center: |
      <a href="https://github.com/tevheath"><i class="bi bi-github"></i></a>
      <a href="mailto:tevinheath.beng@gmail.com"><i class="bi bi-envelope"></i></a>
      <a href="cv/docs/TevH_CV_Eng.pdf"><i class="ai ai-cv"></i></a>
format:
  html:
    theme:
      - cosmo
      - assets/djmquarto.scss
    css: styles.css
    toc: true
    include-in-header: assets/header.html

editor: source


