site_name: TJ Prescod-Heath's Portfolio
site_url: https://mydomain.org/mysite
theme:
  name: material
#  icon:
#    logo: fontawesome/solid/O
  palette:
#    # Palette toggle for automatic mode
#    - media: "(prefers-color-scheme)"
#      toggle:
#        icon: material/brightness-auto
#        name: Switch to light mode
    -
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.integrate
#    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: tags.md
  - blog
#  - git-revision-date-localized: #Updates and creations #Do not include this too much errors
#      enable_creation_date: true

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
#  - pymdownx.arithmatex:
#      generic: true
#
# extra_javascript:
#  - javascripts/extra.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Education & Internships:
    - Education: education/education.md
    - Internship: education/internships.md
#  - Project Management Tools:
#      - Software:
#        - Microsoft Project: pm_tools/Project-Management/microsoft-project.md
#      - Communication:
#        - Microsoft Teams: pm_tools/Communication/microsoft-teams.md
#        - Discord: pm_tools/Communication/discord.md
#        - Slack: pm_tools/Communication/slack.md
#      - Budgeting:
#        - Microsoft Excel: pm_tools/Budgeting/microsoft-excel.md
#      - Strategic Planning:
#        - Microsoft Visio: pm_tools/Strategic-Planning/microsoft-visio.md
#      - Documentation:
#        - Notion: pm_tools/Documentation/notion.md
#        - Overleaf: pm_tools/Documentation/overleaf.md
#  - Projects:
#      - Electrical CAD: projects/Electrical-CAD/Introduction-electrical-cad.md
#      - PCB Design: projects/PCB-Design/Introduction-PCB-Design.md
#      - AI & Machine Learning: projects/AI-Machine-Learning/Introduction-AL-ML.md
#      - Statistical Analysis: projects/Statistical-Analysis/Introduction-Stats.md
#      - Automation: projects/Automation/Introduction-automation.md
#  - Coding Tutorials:
#    - Getting Started:
#        - Installation C++: coding-tutorial/getting-started/installation/installation-cpp.md
#        - Installation C: coding-tutorial/getting-started/installation/installation-c.md
#        - Installation Python: coding-tutorial/getting-started/installation/installation-python.md
#        - Installation MATLAB: coding-tutorial/getting-started/installation/installation-matlab.md
#    - Choosing the Right IDE:
#        - Choose your Preference:
#          - Personal Favourite IDE: coding-tutorial/right-ide/IDE/ide-my-choice.md
#          - VSCode: coding-tutorial/right-ide/IDE/ide-vscode.md
#          - Pycharm: coding-tutorial/right-ide/IDE/ide-pycharm.md
#          - Notepad++: coding-tutorial/right-ide/IDE/ide-notepad.md
#          - Jupyter Notebook: coding-tutorial/right-ide/IDE/ide-jupyter-notebook.md
#          - Anaconda & Spyder: coding-tutorial/right-ide/IDE/ide-spyder.md
#    - Programming Languages: #Note that this is hidden until it is ready
#      - Introduction to C++:
#        - Subsection Item 1: coding-tutorial/getting-started/subsection1.md
#        - Subsection Item 2: coding-tutorial/getting-started/subsection2.md
#      - Introduction to Python:
#        - Subsection Item 1: coding-tutorial/getting-started/subsection1.md
#        - Subsection Item 2: coding-tutorial/getting-started/subsection2.md
#      - Introduction to MATLAB:
#        - Subsection Item 1: coding-tutorial/getting-started/subsection1.md
#        - Subsection Item 2: coding-tutorial/getting-started/subsection2.md
#      - Introduction to Java:
#        - Subsection Item 1: coding-tutorial/getting-started/subsection1.md
#        - Subsection Item 2: coding-tutorial/getting-started/subsection2.
#    - Other Tutorials:
#      - Advanced Python: coding-tutorial/Advanced-Python.md

#  - Internships:
#  - Coding Projects:
#      - Code Tutorials: coding-tutorial/codeblock.md
#      - Computational Tutorials: coding-tutorial/code-tabs.md
#  - Numerical Methods:
#      - Differential Equations (C/C++): tutorials/Computational-Differential-Equations.md
#      - Numerical Methods (C/C++): tutorials/Numerical-Method-CPP.md
#      - Applied Quantitative Algorithms: tutorials/
#      - Computational Physics: tutorials/Numerical-Method-CPP.md
#      - Visible Light Communication: tutorials/Visible-Light-Communication.md
#      - Introduction to C++ - Later move to the Coding tutorials
#      - Introduction to MATLAB
#      - Introduction to Python (Numerical Methods)
#  - Research:
#      - Visible Light Communication: research/Visible-Light-Communication.md

#  - Tags: tags.md
#  - Blog:
#      - blog/index.md
copyright: Copyright &copy; 2025 Tevin Heath

extra:
  social:
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/t-j-prescod-heath-bb9697284/
    - icon: simple/github
      link: https://github.com/TevHeath
  generator: false
#  alternate:
#    - name: English
#      link: /en/
#      lang: en
#    - name: French
#      link: /fr/
#      lang: fr
#    - name: Portuguese
#      link: /pt/
#      lang: pt
#    - name: Italian
#      link: /it/
#      lang: it


