---
title: "Education"
---

Hello world, I'm Tevin - a first-year Bachelor of Engineering Student studying Computer Engineering from the University of Guelph. I am deeply passionate about technology, engineering and control system, and mentoring. I am would like to make the world a better place, while inspiring other to do the same. More details about my work experience and qualifications can be on on LinkedIn at (add url).

---

#### **Bachelor of Engineering in Computer Engineering (Co-op)**
-     The University of Guelph (Sep. 2023 - PRESENT)
    + **Interests**:
        - Hardware Design & Modelling
        - Control System Engineering
        - Electrical Engineering
        - Computer System Design & Networks

\vspace{0.25cm}

#### **Bachelor of Science (Honours) in Mathematics & Statistics**
-     McMaster University (Sep. 2016 -  Jul 2020)
    + **Interests**:
        - Data Science
        - Machine Learning
        - Applied Statistics & Biostatitics
        - Time Series Modelling
        - Statistical Programming


# **Internship Experience**
---
- **Data and Decision Support Intern**, Cambridge Memorial Hospital (June 2022 to Sept 2022)

- **Business & Data Analyst Intern**, Homewood Health Inc. (April 2022 - June 2022)

- **Senior Consultant Intern**, KPMG Canada (October 2021 - May 2022)

- **Municipal Supervisor Intern**, City of London, Ontario (June 2021 - October 2021)

# **Programming Languages**

- C/C++
- C#
- HTML/CSS
- Java
- KQL/SQL
- PHP
- Python


