---
title: "Courses (Guelph Computer Engineering)"
---

Thank you for visiting my courses pages. This pages aims at providing those that read it an ability to see the courses that I was enrolled in second year and above. I will not be sharing my experience in first-year, as it will be different to everyone. Additionally, second-year courses in Computer Engineering begins the process of more specialized coursework that will remain applicable for employeers, peers, and netowkring colleagues. This page will grow iteratively as my 2nd year continues to develop

For potential employer and recruiters interest:


-   The programming course of ENGG 1410 utilizes and instructs the low-level programming language of the C and C++.




# FALL 2024


## Engineering Design

#### [ENGG 1100 - Engineering and Design I](fall_2023/eng1100.qmd)

#### [ENGG 1410 - Intro to Programming for Engineers (C/C++)](fall_2023/eng1410.qmd)


## First Principles Sciences

#### [PHYSICS 1130 - Physics with Applications](fall_2023/phys1130.qmd)

#### [MATH 1200 - Calculus I](fall_2023/math1200.qmd)

<!-- ## Chemistry -->

<!-- #### [CHEM 1040 - General Chemistry I](fall_2023/chem1040.qmd) -->

# WINTER 2024


## Engineering Design

#### ENGG 1210 - Engineering Mechanics I

<!-- #### ENGG 1420 - Object-Oriented Programming for Engineers (Java) -->

#### ENGG 1500 - Engineering Analysis 

## First Principles Sciences

#### MATH 1210 - Calculus II

#### PHYS 1010 - Introductory Electricity and Magnestism
